# SPDX-FileCopyrightText: Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>
# SPDX-License-Identifier: CC0-1.0 OR MIT
# Source: <https://reuse.software/>

version = 1
SPDX-PackageName = "oeo"
SPDX-PackageSupplier = "Ludwig Hülk <https://github.com/Ludee>"
SPDX-PackageDownloadLocation = "https://github.com/OpenEnergyPlatform/ontology"
SPDX-PackageComment = "This work is licensed under Creative Commons Zero v1.0 Universal (CC0-1.0) or MIT License (MIT)."

[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"
SPDX-FileComment = "Copyright: OEO documentation licensed CC0-1.0"

[[annotations]]
path = ".github/ISSUE_TEMPLATE/*.md"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = ".github/pull_request_template.md"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = ".github/*.yml"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "examples/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "examples/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "src/ontology/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "src/scripts/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "tests/**"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "Makefile"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"

[[annotations]]
path = "VERSION"
precedence = "override"
SPDX-FileCopyrightText = "Open Energy Ontology (OEO) <https://github.com/OpenEnergyPlatform/ontology/>"
SPDX-License-Identifier = "CC0-1.0 OR MIT"
