# SPDX-FileCopyrightText: 2026 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: OEO <https://github.com/OpenEnergyPlatform/ontology>
# SPDX-License-Identifier: MIT

name: 📝 Documentation (production branch)

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: actions/cache@v5
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install --upgrade -r requirements.txt
      - run: mkdocs gh-deploy --force
