name: Move issues to "In discussion" project column
on:
  issues: 
    types: [labeled]

jobs:
  moveIssueToInDiscussionColumn:
    if: github.event_name == 'issues' && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - uses: PaperMC/update-projects-action@v0.2.0
        with:
          github-token: "${{ secrets.OEO_WORKFLOWS }}"
          project-url: https://github.com/orgs/OpenEnergyPlatform/projects/45/views/1
          column-field: Status
          clear-on-no-match: false
          label-to-column-map: |
            {
              "To do": "To do",
              "in discussion": "In discussion"
            }